services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3     
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile # Використовуємо продакшн-файл
      ports:
        - "80:80"
      depends_on:
        - backend
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    volumes:
      - coverage_data:/app/coverage

volumes:
  coverage_data: