sonar.projectKey=Zhuravka-AI_devops-playground
sonar.organization=zhuravka-ai
sonar.host.url=https://sonarcloud.io

sonar.sources=backend,frontend

sonar.exclusions=**/node_modules/**,**/dist/**,**/venv/**,**/*.test.jsx,**/test_*.py
sonar.coverage.exclusions=frontend/src/main.jsx, frontend/src/setupTests.js, frontend/src/components/SentryTest.jsx

sonar.tests=backend/app,frontend/src
sonar.test.inclusions=**/*.test.jsx,**/test_*.py
sonar.python.version=3.12

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.scm.disabled=false
sonar.language=py
sonar.sourceEncoding=UTF-8