sonar.projectKey=Zhuravka-AI_devops-playground
sonar.organization=zhuravka-ai
sonar.sources=backend/app
sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.language=py
sonar.sourceEncoding=UTF-8