name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Run Backend Tests
        run: |
          docker compose build backend
          touch backend/coverage.xml
          docker compose run \
            -v $(pwd)/backend/coverage.xml:/app/coverage.xml \
            backend python -m pytest --cov=app --cov-report=xml:coverage.xml
          
          sed -i 's|<source>.*</source>|<source>./</source>|g' backend/coverage.xml
          sed -i 's|filename="|filename="backend/app/|g' backend/coverage.xml
      
      - name: Upload Backend Coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.xml

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Run Frontend Tests
        run: |
          # Білдимо образ для тестів
          docker build -t frontend-tests -f frontend/Dockerfile.test frontend/
          
          mkdir -p frontend/coverage
          docker run --rm \
            -v $(pwd)/frontend/coverage:/app/coverage \
            frontend-tests
      
      - name: Upload Frontend Coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage/lcov.info

  sonarcloud:
    needs: [backend-test, frontend-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Download Backend Coverage
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage
          path: backend
      - name: Download Frontend Coverage
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=backend/coverage.xml
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

  deploy:
    name: Deploy to Render
    needs: [sonarcloud]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -f ${{ secrets.RENDER_DEPLOY_HOOK }}